ZFIN-8771 & ZFIN-8772: UniProt Diff-Based Load including reports and jenkins jobs (#801)
* ZFIN-8073:

Add gradle command "uniprotFilterTask" that can be used to filter a UniProt dat file and output the contents of the file without any of the fields we don't care about.  Example:

UNIPROT_INPUT_FILE=/tmp/pre_zfin.dat UNIPROT_OUTPUT_FILE=/tmp/pre_zfin.filtered.dat gradle uniprotFilterTask

- Introduce task to compare 2 uniprot dat files and generate report.

Modify UniProtFormatZFIN:
- Filter uniprot dat file to only include the information we need. Preserve the sequence length in the "ID" line (aka locus line).
- remove empty lines from output
- remove sequence section if none

* ZFIN-8771: table definition

* ZFIN-8771: Add constants for uniprot paths (local and remote)

* ZFIN-8073: Add a report template for presenting diffs.

* ZFIN-8073: Add a first pass on taxon filtering that doesn't need to parse the full record.

- Remove main class from filter task. It can be invoked from uniprotReleaseDiffTask
- Fix compiler errors in github actions. We were getting errors that indicate that java can't figure out the types.

Example error:
```
compile:
     [copy] Copying 298 files to /home/runner/work/zfin/zfin/home/WEB-INF/classes
    [javac] Compiling 2219 source files to /home/runner/work/zfin/zfin/home/WEB-INF/classes
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/UniProtAnalysisTask.java:108: error: cannot find symbol
    [javac]                     .filter(rankedXref -> "RefSeq".equals(rankedXref.getCrossRef().getDbname()))
    [javac]                                                                     ^
    [javac]   symbol:   method getCrossRef()
    [javac]   location: variable rankedXref of type Object
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/UniProtAnalysisTask.java:111: error: cannot find symbol
    [javac]                             rankedXref.getCrossRef().getAccession().replaceAll("\\.\\d*", "")
    [javac]                                       ^
    [javac]   symbol:   method getCrossRef()
    [javac]   location: variable rankedXref of type Object
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/diff/RichSequenceDiff.java:66: error: cannot find symbol
    [javac]         Set<CrossRef> xrefs1 = seq1.getRankedCrossRefs().stream().map(xref -> xref.getCrossRef()).collect(Collectors.toSet());
    [javac]                                                                                   ^
    [javac]   symbol:   method getCrossRef()
    [javac]   location: variable xref of type Object
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/diff/RichSequenceDiff.java:66: error: incompatible types: Object cannot be converted to Set<CrossRef>
    [javac]         Set<CrossRef> xrefs1 = seq1.getRankedCrossRefs().stream().map(xref -> xref.getCrossRef()).collect(Collectors.toSet());
    [javac]                                                                                                          ^
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/diff/RichSequenceDiff.java:67: error: cannot find symbol
    [javac]         Set<CrossRef> xrefs2 = seq2.getRankedCrossRefs().stream().map(xref -> xref.getCrossRef()).collect(Collectors.toSet());
    [javac]                                                                                   ^
    [javac]   symbol:   method getCrossRef()
    [javac]   location: variable xref of type Object
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/diff/RichSequenceDiff.java:67: error: incompatible types: Object cannot be converted to Set<CrossRef>
    [javac]         Set<CrossRef> xrefs2 = seq2.getRankedCrossRefs().stream().map(xref -> xref.getCrossRef()).collect(Collectors.toSet());
    [javac]                                                                                                          ^
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/UniProtFilterTask.java:82: error: incompatible types: Object cannot be converted to RankedCrossRef
    [javac]                 for (RankedCrossRef rankedCrossRef : seq.getRankedCrossRefs()) {
    [javac]                                                                            ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 7 errors
```

* ZFIN-8771: Use DTOs instead of custom serializers

* ZFIN-8771: Create pipeline structure around various rules

In order to isolate the various types of load logic, I created the
"pipeline" construct that allows us to append "Handlers". Each can
access the entire set of incoming uniprot records and existing records
and use their own internal logic to create "actions".

* ZFIN-8771: Add load reports as html files

* ZFIN-8771: Introduce some adapter classes

* ZFIN-8771: Use Set instead of List for uniqueness. update non-curated pub list
- include publication IDs with DBLinks
- add db name to DBLinks
- Use DB queries to determine if dblinks are non-load pubs

* ZFIN-8771: Add UniProt-Release-Check daily job

* ZFIN-8771: Add jenkins job jobs/UniProt-Release-Check_d

* ZFIN-8771: Break down errors into even more granular types.  Add jenkins job check-recent-uniprot-release.
Trigger downstream job.

* ZFIN-8771: Add UniProt-Diff-Load -- the actual load job

* ZFIN-8771: Apply suggestions from code inspection from intellij

* ZFIN-8771: Clean up and add comments

* ZFIN-8771: Add an option to write the context out as a json artifact.

Since this whole load is deterministic based on the DB context and the load file, retaining old context files can give us a history that we can use for tests and troubleshooting issues.

* ZFIN-8771: Tweak to account for no release date on API urls
ZFIN-8771: Use standard names for download files of uniprot
ZFIN-8771: Update java defaults to reflect trembl/sprot distinction

* ZFIN-8771: Update log message

* - hide noisy log messages
- remove redundant library log4j-slf4j-impl (2.9.0 & 2.13.3)
- fix path of hibernate-c3p0-5.6.5.Final.jar

* ZFIN-8771: Add the action to queue