ZFIN-8073: Add a first pass on taxon filtering that doesn't need to parse the full record.
- Remove main class from filter task. It can be invoked from uniprotReleaseDiffTask
- Fix compiler errors in github actions. We were getting errors that indicate that java can't figure out the types.

Example error:
```
compile:
     [copy] Copying 298 files to /home/runner/work/zfin/zfin/home/WEB-INF/classes
    [javac] Compiling 2219 source files to /home/runner/work/zfin/zfin/home/WEB-INF/classes
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/UniProtAnalysisTask.java:108: error: cannot find symbol
    [javac]                     .filter(rankedXref -> "RefSeq".equals(rankedXref.getCrossRef().getDbname()))
    [javac]                                                                     ^
    [javac]   symbol:   method getCrossRef()
    [javac]   location: variable rankedXref of type Object
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/UniProtAnalysisTask.java:111: error: cannot find symbol
    [javac]                             rankedXref.getCrossRef().getAccession().replaceAll("\\.\\d*", "")
    [javac]                                       ^
    [javac]   symbol:   method getCrossRef()
    [javac]   location: variable rankedXref of type Object
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/diff/RichSequenceDiff.java:66: error: cannot find symbol
    [javac]         Set<CrossRef> xrefs1 = seq1.getRankedCrossRefs().stream().map(xref -> xref.getCrossRef()).collect(Collectors.toSet());
    [javac]                                                                                   ^
    [javac]   symbol:   method getCrossRef()
    [javac]   location: variable xref of type Object
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/diff/RichSequenceDiff.java:66: error: incompatible types: Object cannot be converted to Set<CrossRef>
    [javac]         Set<CrossRef> xrefs1 = seq1.getRankedCrossRefs().stream().map(xref -> xref.getCrossRef()).collect(Collectors.toSet());
    [javac]                                                                                                          ^
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/diff/RichSequenceDiff.java:67: error: cannot find symbol
    [javac]         Set<CrossRef> xrefs2 = seq2.getRankedCrossRefs().stream().map(xref -> xref.getCrossRef()).collect(Collectors.toSet());
    [javac]                                                                                   ^
    [javac]   symbol:   method getCrossRef()
    [javac]   location: variable xref of type Object
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/diff/RichSequenceDiff.java:67: error: incompatible types: Object cannot be converted to Set<CrossRef>
    [javac]         Set<CrossRef> xrefs2 = seq2.getRankedCrossRefs().stream().map(xref -> xref.getCrossRef()).collect(Collectors.toSet());
    [javac]                                                                                                          ^
    [javac] /home/runner/work/zfin/zfin/source/org/zfin/uniprot/UniProtFilterTask.java:82: error: incompatible types: Object cannot be converted to RankedCrossRef
    [javac]                 for (RankedCrossRef rankedCrossRef : seq.getRankedCrossRefs()) {
    [javac]                                                                            ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 7 errors
```