ZFIN-9916 and ZFIN-9994 and ZFIN-9933: groovy and gradle fixes (#1650)
* ZFIN-9933: Gradle upgrade but downgrade to match deps (#21)

* progress toward war packaging
upgrade lucene api usage
delete unneeded jars
Remove embedded jackson lib in robot.jar to fix error:

    java.lang.NoSuchMethodError: 'com.fasterxml.jackson.databind.cfg.MutableCoercionConfig com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()'
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:184)
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:153)
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:135)
        at org.hibernate.type.format.jackson.JacksonXmlFormatMapper.createXmlMapper(JacksonXmlFormatMapper.java:46)
        at org.hibernate.type.format.jackson.JacksonXmlFormatMapper.<init>(JacksonXmlFormatMapper.java:38)
        at org.hibernate.type.format.jackson.JacksonIntegration.<clinit>(JacksonIntegration.java:17)

* remove angular directive files

ZFIN-9994: Remove unneeded jar files. restygwt is necessary because there is no upstream version with jakarta
ZFIN-9994: re-add javassist because it is needed by gwt (see FeatureAddView import javassist.compiler.ast.StringL)
ZFIN-9994: Remove log4j references (replaced with log4j2)
ZFIN-9994: Remove directories from settings.gradle if they do not contain build.gradle
ZFIN-9994: Do not need explicit "AntBuilder()" constructor invocation in new version of ant <groovy> taskdef
ZFIN-9994: Create a warfile for deployment
ZFIN-9994: Add an application target so we can run tasks without gradle
ZFIN-9994: Remove analytics uberjar from local repo
ZFIN-9994: Remove outdated deploy targets
ZFIN-9994: Add gradle tasks to reload class files quickly after code changes
ZFIN-9994: Remove static files that are not needed in the war file (they are served by apache)
ZFIN-9994: Use database to store release version information
ZFIN-9994: Remove pre-home / post-home logic
* Upgrade groovy in github action
* use maven for text-table-formatter
* remove cvu.jar as it is not used anymore (only reference is unused)
* update to match newer names
* Update paths for WAR file deployment compatibility

   - Add ZFIN_PROPERTIES_PATH env var pointing to deployed WAR location
   - Update GROOVY_CLASSPATH to use CATALINA_BASE/webapps/ROOT/WEB-INF
   - Update ~45 Groovy scripts to use ZFIN_PROPERTIES_PATH
   - Update ZFINPerlModules.pm to use ZFIN_PROPERTIES_PATH
   - Update Jenkins job configs with new properties file paths
   - Fix Groovy 4.x compatibility: use groovy.xml.XmlSlurper and
     groovy.xml.slurpersupport.GPathResult imports

* ZFIN-9994: remove legacy biojava
* ZFIN-9994: use gradle for test
* ZFIN-9994: use $WAR_WEB_INF_DIR to reference the deployment location of WEB-INF
* ZFIN-9916: Introduce new classpath values for the deployed location of jars
* ZFIN-9916: Remove log4j version 1 formatting
* ZFIN-9916: Fix errors in output:

```
Buildfile: /opt/zfin/source_roots/zfin.org/build.xml
  [taskdef] ERROR StatusConsoleListener root contains an invalid element or attribute "priority"
  [taskdef] ERROR StatusConsoleListener Unknown object "root" of type org.apache.logging.log4j.core.config.LoggerConfig is ignored: try nesting it inside one of: ["Appenders", "Loggers", "Properties", "Scripts", "CustomLevels"].
```

* ZFIN-9916: fix classpath issues for ant
* ZFIN-9916: fix JDBC connection issues for solr
* ZFIN-9916: Remove "grand" library. Include message for instructions if we want to re-include it.
* ZFIN-9916: Use "$HOME" instead of /home/gradle for files that have access to env vars.