ZFIN-9933 and ZFIN-9994: Update gradle task to use war and fewer libraries (#1626)
* ZFIN-9933: Gradle upgrade but downgrade to match deps (#21)

* progress toward war packaging
upgrade lucene api usage
delete unneeded jars
Remove embedded jackson lib in robot.jar to fix error:

    java.lang.NoSuchMethodError: 'com.fasterxml.jackson.databind.cfg.MutableCoercionConfig com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()'
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:184)
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:153)
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:135)
        at org.hibernate.type.format.jackson.JacksonXmlFormatMapper.createXmlMapper(JacksonXmlFormatMapper.java:46)
        at org.hibernate.type.format.jackson.JacksonXmlFormatMapper.<init>(JacksonXmlFormatMapper.java:38)
        at org.hibernate.type.format.jackson.JacksonIntegration.<clinit>(JacksonIntegration.java:17)

* remove angular directive files

ZFIN-9994: delete unneeded jars

ZFIN-9994: Remove unneeded jar files. restygwt is necessary because there is no upstream version with jakarta
ZFIN-9994: re-add javassist because it is needed by gwt (see FeatureAddView import javassist.compiler.ast.StringL)
ZFIN-9994: Remove log4j references (replaced with log4j2)
ZFIN-9994: Remove directories from settings.gradle if they do not contain build.gradle
ZFIN-9994: Do not need explicit "AntBuilder()" constructor invocation in new version of ant <groovy> taskdef
ZFIN-9994-warversion: Create a warfile for deployment
ZFIN-9994-warversion: Add an application target so we can run tasks without gradle
ZFIN-9994-warversion: Remove analytics uberjar from local repo

* ZFIN-9994: Remove autodeploy

* ZFIN-9994: Remove outdated deploy targets

* ZFIN-9994: Add gradle tasks to reload class files quickly after code changes
ZFIN-9994: Fix deprecated setting for destination dir
ZFIN-9994: Add dirtydeploy task again.
ZFIN-9994: Fix dependency needed for tests

* ZFIN-9994: Remove static files that are not needed in the war file (they are served by apache)

* ZFIN-9994: Use database to store release version information

* ZFIN-9994: Remove pre-home / post-home logic

* ZFIN-9994: Be consistent in naming releaseNumber instead of releaseVersion

* Upgrade groovy in github action

* use maven for text-table-formatter

* remove cvu.jar as it is not used anymore (only reference is unused)

* remove jars

* update to match newer names

* do not fail build if deployGitInfo fails

* Add more captcha blocking logic (on POSTs)

* ZFIN-9994: Fix `gradle runEnsemblTranscriptLengthUpdater` issue